ServerEvents.recipes(event => {
    event.remove([
		{ output: 'productivebees:centrifuge' },
		{ output: 'productivebees:bottler' },
		{ output: 'productivebees:powered_centrifuge' },
		{ output: 'productivebees:honey_generator' },
		{ output: 'productivebees:catcher' },
		{ output: 'productivebees:gene_indexer' },
		{ output: 'productivebees:breeding_chamber' },
		{ output: 'productivebees:incubator' },
		{ output: 'productivebees:heated_centrifuge' },
		{ output: 'minecraft:beehive' },
		{ output: 'productivebees:upgrade_base' },
		{ output: 'productivebees:upgrade_time' },
		{ output: 'productivebees:upgrade_anti_teleport' },
		{ output: 'productivebees:upgrade_bee_sampler' },
		{ output: 'productivebees:upgrade_breeding' },
		{ output: 'productivebees:upgrade_breeding' },
		{ output: 'productivebees:upgrade_filter' },
		{ output: 'productivebees:upgrade_productivity' },
		{ output: 'productivebees:upgrade_range' },
		{ output: 'productivebees:upgrade_simulator' },
		{ output: 'productivebees:upgrade_comb_block' },
		{ output: 'productivebees:advanced_jungle_beehive' },
		{ output: 'productivebees:expansion_box_jungle' },
		{ output: 'productivebees:advanced_snake_block_beehive' },
		{ output: 'productivebees:expansion_box_snake_block' },
		{ output: 'productivebees:advanced_spruce_beehive' },
		{ output: 'productivebees:expansion_box_spruce' },
		{ output: 'productivebees:advanced_warped_beehive' },
		{ output: 'productivebees:expansion_box_warped' },
		{ output: 'productivebees:advanced_oak_beehive' },
		{ output: 'productivebees:expansion_box_oak' },
		{ output: 'productivebees:advanced_dark_oak_beehive' },
		{ output: 'productivebees:expansion_box_dark_oak' },
		{ output: 'productivebees:advanced_crimson_beehive' },
		{ output: 'productivebees:expansion_box_crimson' },
		{ output: 'productivebees:advanced_birch_beehive' },
		{ output: 'productivebees:expansion_box_birch' },
		{ output: 'productivebees:advanced_acacia_beehive' },
		{ output: 'productivebees:expansion_box_acacia' }


    ])
})