StartupEvents.registry('block', event => {
    event.create('gribtweaks:comb_infinity')
    .soundType('metal')
    .hardness(0.6)
    .displayName('Блок Бесконечных сот') 
    .tagBlock('forge:storage_blocks') 
    .tagBlock('forge:storage_blocks/honeycombs')
    .requiresTool(false)
  
    event.create('gribtweaks:comb_neutronium')
    .hardness(0.6)
    .displayName('Блок нейтроных сот') 
    .tagBlock('forge:storage_blocks') 
    .tagBlock('forge:storage_blocks/honeycombs')
    .requiresTool(false)
    
    event.create('ad_astra:reinforced_covering')
    .soundType('stone')
    .hardness(0.8)
    .displayName('§6Reinforced Covering') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_diamond_tool')
    .requiresTool(true)

    event.create('ad_astra:advanced_covering')
    .soundType('stone')
    .hardness(0.8)
    .displayName('§5Advanced Covering') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_diamond_tool')
    .requiresTool(true)

    event.create('ad_astra:ultra_covering')
    .soundType('stone')
    .hardness(0.8)
    .displayName('§cUltra Covering') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_diamond_tool')
    .requiresTool(true)

    event.create('botania:life_essence_block')
    .material('metal')
    .hardness(1.5)
    .displayName('§bLife Essence Block') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_diamond_tool')
    .requiresTool(true)
})