ServerEvents.recipes(event => {
    event.remove([
        { output: 'ae2:inscriber' },
        { output: 'ae2:fluid_cell_housing' },
        { output: 'ae2:item_cell_housing' },
        { output: 'appbot:mana_cell_housing' },
        { output: 'ae2things:disk_housing' },
        { output: 'megacells:mega_fluid_cell_housing' },
        { output: 'megacells:mega_item_cell_housing' },
		{ output: 'ae2:cell_component_1k' },
		{ output: 'ae2things:disk_drive_1k' },
		{ output: 'ae2:item_storage_cell_1k' },
		{ output: 'appbot:mana_storage_cell_1k' },
		{ output: 'ae2:fluid_storage_cell_1k' },
		{ output: 'ae2things:disk_drive_4k' },
		{ output: 'ae2:item_storage_cell_4k' },
		{ output: 'appbot:mana_storage_cell_4k' },
		{ output: 'ae2:fluid_storage_cell_4k' },
        { output: 'ae2:cell_component_4k' },
		{ output: 'ae2things:disk_drive_16k' },
		{ output: 'ae2:item_storage_cell_16k' },
		{ output: 'appbot:mana_storage_cell_16k' },
		{ output: 'ae2:fluid_storage_cell_16k' },
        { output: 'ae2:cell_component_16k' },
		{ output: 'ae2things:disk_drive_64k' },
		{ output: 'ae2:item_storage_cell_64k' },
		{ output: 'appbot:mana_storage_cell_64k' },
		{ output: 'ae2:fluid_storage_cell_64k' },
        { output: 'ae2:cell_component_64k' },
		{ output: 'ae2things:disk_drive_256k' },
		{ output: 'ae2:item_storage_cell_256k' }, 
		{ output: 'appbot:mana_storage_cell_256k' }, 
		{ output: 'ae2:fluid_storage_cell_256k' },
        { output: 'ae2:cell_component_256k' }, 
		{ output: 'megacells:item_storage_cell_1m' },
        { output: 'megacells:fluid_storage_cell_1m' }, 
		{ output: 'megacells:item_storage_cell_4m' },
        { output: 'megacells:fluid_storage_cell_4m' }, 
		{ output: 'megacells:item_storage_cell_16m' },
        { output: 'megacells:fluid_storage_cell_16m' }, 
		{ output: 'megacells:item_storage_cell_64m' },
        { output: 'megacells:fluid_storage_cell_64m' }, 
		{ output: 'megacells:item_storage_cell_256m' },
        { output: 'megacells:fluid_storage_cell_256m' },
		{ output: 'megacells:cell_component_1m' },  
		{ output: 'megacells:cell_component_4m' },
		{ output: 'megacells:cell_component_16m' },
		{ output: 'megacells:cell_component_64m' },
        { output: 'megacells:cell_component_256m' }

    ])
})