ServerEvents.recipes(event => {
	const output = [
		'ae2:inscriber',
        'ae2:fluid_cell_housing',
        'ae2:item_cell_housing',
        'appbot:mana_cell_housing',
        'ae2things:disk_housing',
        'megacells:mega_fluid_cell_housing',
        'megacells:mega_item_cell_housing',
		'ae2:cell_component_1k',
		'ae2things:disk_drive_1k',
		'ae2:item_storage_cell_1k',
		'appbot:mana_storage_cell_1k',
		'ae2:fluid_storage_cell_1k',
		'ae2things:disk_drive_4k',
		'ae2:item_storage_cell_4k',
		'appbot:mana_storage_cell_4k',
		'ae2:fluid_storage_cell_4k',
        'ae2:cell_component_4k',
		'ae2things:disk_drive_16k',
		'ae2:item_storage_cell_16k',
		'appbot:mana_storage_cell_16k',
		'ae2:fluid_storage_cell_16k',
        'ae2:cell_component_16k',
		'ae2things:disk_drive_64k',
		'ae2:item_storage_cell_64k',
		'appbot:mana_storage_cell_64k',
		'ae2:fluid_storage_cell_64k',
        'ae2:cell_component_64k',
		'ae2things:disk_drive_256k',
		'ae2:item_storage_cell_256k' ,
		'appbot:mana_storage_cell_256k' ,
		'ae2:fluid_storage_cell_256k',
        'ae2:cell_component_256k', 
		'megacells:item_storage_cell_1m',
        'megacells:fluid_storage_cell_1m' ,
		'megacells:item_storage_cell_4m',
        'megacells:fluid_storage_cell_4m' ,
		'megacells:item_storage_cell_16m',
        'megacells:fluid_storage_cell_16m' ,
		'megacells:item_storage_cell_64m',
        'megacells:fluid_storage_cell_64m' ,
		'megacells:item_storage_cell_256m',
        'megacells:fluid_storage_cell_256m',
		'megacells:cell_component_1m'  ,
		'megacells:cell_component_4m',
		'megacells:cell_component_16m',
		'megacells:cell_component_64m',
        'megacells:cell_component_256m',
    ]


    output.forEach(recipe => {
        event.remove({output: recipe})
    })
})