#Whether or not bonemeal should be consumed when used in a biome with bonemeal use disabled.
"Consume Bonemeal" = false

[Output]
	#If true, BiomeTweaker will output separate files for each object (e.g., biomes)
	"Separate Files" = true
	#Whether or not BiomeTweaker should output biome info. You can turn this off if you don't need it to shave output time.
	#You must run the biometweaker output command in game.
	Biomes = true
	#Whether or not BiomeTweaker should output entity info. You can turn this off if you don't need it to shave output time.
	#You must run the biometweaker output command in game.
	Entities = true
	#Whether or not BiomeTweaker should output dimension info. You can turn this off if you don't need it to shave output time.
	#You must run the biometweaker output command in game.
	Dimensions = true
	#Whether or not BiomeTweaker should output feature info. You can turn this off if you don't need it to shave output time.
	#You must run the biometweaker output command in game.
	Features = true
	#Whether or not BiomeTweaker should output carver info. You can turn this off if you don't need it to shave output time.
	#You must run the biometweaker output command in game.
	Carvers = true

