
#Settings for the mechanical spawner
[mechanical_spawner]
	#Stress impact
	#Range: 0.0 ~ 64.0
	stressImpact = 16.0
	#Minimum required speed
	#Range: 0.0 ~ 2.147483647E9
	minimumSpeed = 100.0
	#Liquid capacity
	#Range: > 1
	liquidCapacity = 1000

