StartupEvents.registry('block', e => {
    e.create('ad_astra:reinforced_covering')
    .material('iron')
    .hardness(0.8)
    .displayName('§6Reinforced Covering') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_diamond_tool')
    .requiresTool(true)

    e.create('ad_astra:advanced_covering')
    .material('iron')
    .hardness(0.8)
    .displayName('§5Advanced Covering') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_diamond_tool')
    .requiresTool(true)

    e.create('ad_astra:ultra_covering')
    .material('iron')
    .hardness(0.8)
    .displayName('§cUltra Covering') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_diamond_tool')
    .requiresTool(true)

    e.create('botania:life_essence_block')
    .material('metal')
    .hardness(1.5)
    .displayName('§bLife Essence Block') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_diamond_tool')
    .requiresTool(true)
})