StartupEvents.registry('block', event => {
    // Gribony
    event.create('chemlib:gribony_block')
    .soundType('metal')
    .hardness(50)
    .displayName('§4§lБлок Грибония') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_diamond_tool')
    .tagBlock('minecraft:beacon_base_blocks')
    .tagBlock('forge:storage_blocks')
    .requiresTool(true)
    .lightLevel(0.6)
    .item(itemBuilder => {
        itemBuilder
            .group('chemlib.metals')
            .tooltip('§bGb (21682)')
            .tooltip('§7Переходные Металлы')
    })

    event.create('chemlib:unstable_gribony_block')
    .soundType('metal')
    .hardness(10)
    .displayName('§e§lБлок нестабильного Грибония') 
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_diamond_tool')
    .tagBlock('forge:storage_blocks') 
    .requiresTool(true)
    .item(itemBuilder => {
        itemBuilder
            .group('chemlib.metals')
            .tooltip('§7Безопасное вещество')
    })

    event.create('chemlib:pre_gribony_block')
    .soundType('metal')
    .hardness(25)
    .displayName('§5§lБлок Пре-Грибония') 
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_diamond_tool')
    .tagBlock('forge:storage_blocks') 
    .requiresTool(true)
    .item(itemBuilder => {
        itemBuilder
            .group('chemlib.metals')
            .tooltip('§bPGb (10841)')
            .tooltip('§7Переходные Металлы')
    })

    // stage 1
    event.create('gribtweaks:ash_block')
    .soundType('sand')
    .hardness(0.5)
    .displayName('Блок золы') 
    .tagBlock('minecraft:mineable/shovel')
    .requiresTool(false)

    event.create('gribtweaks:compressed_ash_block')
    .soundType('sand')
    .hardness(2)
    .displayName('Сжатый блок золы') 
    .tagBlock('minecraft:mineable/shovel')
    .requiresTool(false)
    // stage 5
    event.create('gribtweaks:advanced_casing')
    .soundType('metal')
    .hardness(10)
    .displayName('Совершенный корпус') 
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .requiresTool(true)
    // stage 6
    event.create('ad_astra:protasteel_block')
    .soundType('metal')
    .hardness(5)
    .displayName('Прота-стальной блок') 
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('forge:storage_blocks') 
    .requiresTool(true)

    event.create('ad_astra:rocket_covering')
    .soundType('metal')
    .hardness(5)
    .displayName('Обшивка ракеты') 
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .requiresTool(true)

    event.create('biggerreactors:reinforced_ludicrite_block')
    .soundType('metal')
    .hardness(10)
    .displayName('Усиленный лудикритовый блок') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_diamond_tool')
    .tagBlock('forge:storage_blocks')
    .requiresTool(true)

    // other 
    event.create('gribtweaks:triple_compressed_crafting_table')
    .soundType('wood')
    .hardness(5)
    .displayName('Трижды сжатый верстак') 
    .tagBlock('minecraft:mineable/axe') 
    
    event.create('gribtweaks:quadruple_compressed_crafting_table')
    .soundType('wood')
    .hardness(5)
    .displayName('Четырежды сжатый верстак') 
    .tagBlock('minecraft:mineable/axe') 

    event.create('gribtweaks:oblivion_block')
    .soundType('metal')
    .hardness(10)
    .displayName('§aБлок Забвения') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('forge:storage_blocks')
    .requiresTool(true)

    event.create('gribtweaks:void_block')
    .soundType('metal')
    .hardness(10)
    .displayName('Пустотный блок') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('forge:storage_blocks')
    .requiresTool(true)

    event.create('gribtweaks:anxiety_block')
    .soundType('metal')
    .hardness(10)
    .displayName('Блок Тревоги') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('forge:storage_blocks')
    .requiresTool(true)

    event.create('gribtweaks:death_block')
    .soundType('metal')
    .hardness(10)
    .displayName('Блок Смерти') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('forge:storage_blocks')
    .requiresTool(true)

    event.create('gribtweaks:admiration_block')
    .soundType('metal')
    .hardness(10)
    .displayName('Блок Восхищения') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('forge:storage_blocks')
    .requiresTool(true)

    event.create('gribtweaks:ametrine_ore')
    .soundType('stone')
    .hardness(3)
    .displayName('Аметриновая руда') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_diamond_tool')
    .tagBlock('forge:ores')
    .requiresTool(true)

    event.create('gribtweaks:ametrine_block')
    .soundType('metal')
    .hardness(5)
    .displayName('§dАметриновый блок') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_iron_tool')
    .requiresTool(true)

    event.create('gribtweaks:ametrine_bricks')
    .soundType('metal')
    .hardness(5)
    .displayName('§dАметриновые кирпичи') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('forge:storage_blocks')
    .requiresTool(true)

    event.create('gribtweaks:polished_ametrine_block')
    .soundType('metal')
    .hardness(5)
    .displayName('§dПолированный аметриновый блок') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_iron_tool')
    .requiresTool(true)

    event.create('gribtweaks:elemental_fragments_block')
    .soundType('stone')
    .hardness(0.5)
    .displayName('§bБлок элементальных фрагментов') 

    // end game
    event.create('gribtweaks:ultimate_block')
    .soundType('metal')
    .hardness(50)
    .displayName('§bМаксимальный блок') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('minecraft:beacon_base_blocks')
    .tagBlock('forge:storage_blocks')
    .requiresTool(true)
    .lightLevel(0.6)
    .item(itemBuilder => {
        itemBuilder
            .tooltip('§7Поражает то, что вы можете поднять его')
    })

    event.create('gribtweaks:true_infinity_block')
    .soundType('metal')
    .hardness(25)
    .displayName('§cИстинный блок Бесконечности') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('forge:storage_blocks')
    .requiresTool(true)

    event.create('gribtweaks:blaze_cell')
    .soundType('metal')
    .hardness(1)
    .displayName('Клетка с Ифритом') 
    .item(itemBuilder => {
        itemBuilder
            .tooltip('§7При разрушении появляются ифриты. (от 0 до 8 существ)')
    })

    event.create('gribtweaks:block_infinity_catalyst')
    .soundType('metal')
    .hardness(30)
    .lightLevel(1)
    .displayName('§cБесконечный блок катализаторов') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('forge:storage_blocks')
    .requiresTool(true)

    event.create('gribtweaks:infinity_heavy_cogwheel')
    .soundType('metal')
    .hardness(20)
    .lightLevel(0.6)
    .displayName('§dБесконечно-тяжелая шестерня')
    .item(itemBuilder => {
        itemBuilder
            .tooltip('§7Не может использоваться как обычная шестерня!')
    })
    .defaultTranslucent()

    event.create('gribtweaks:compressed_knightmetal_block')
    .soundType('metal')
    .hardness(15)
    .lightLevel(0.1)
    .displayName('Сжатый блок королевского металла')
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('minecraft:beacon_base_blocks')
    .tagBlock('forge:storage_blocks')
    .requiresTool(true)
    .defaultTranslucent()

    event.create('gribtweaks:compressed_fiery_block')
    .soundType('metal')
    .hardness(10)
    .lightLevel(0.1)
    .displayName('Сжатый блок огненного металла')
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('minecraft:beacon_base_blocks')
    .tagBlock('forge:storage_blocks')
    .requiresTool(true)
    .defaultTranslucent()
})
