Ponder.registry(e => {
    e
        .create([
            /minecraft:\w+concrete/
        ])
        .scene('tm4:concrete_farm', "Concrate Farm!", 'quark_concrete_farm', (scene, util) => {
            scene.scaleSceneView(.8);
            scene.addKeyframe()
            scene.idle(0)
            scene.world.showSection(util.select.fromTo(0,0,0,11,0,11), Facing.DOWN)
            scene.world.showSection(util.select.fromTo(0,1,2,3,1,11), Facing.DOWN)
            scene.world.showSection(util.select.fromTo(10,1,10,4,1,6), Facing.DOWN)
            scene.overlay.showText(60)
                .colored(PonderPalette.RED)
                .text("The best concrete farm!")
                .placeNearTarget();
            scene.idle(60)
            scene.addKeyframe()
            scene.idle(0)
            scene.world.showSection(util.select.fromTo(5,1,1,4,1,1), Facing.DOWN)
            scene
                .text(40, "Place 2 chests", [4, 1,1])
                .colored(PonderPalette.WHITE)
                .placeNearTarget()
            scene.idle(40)
            scene.addKeyframe()
            scene.idle(0)
            scene.rotateCameraY(100);
            scene.idle(20)
            scene.idle(0)
            scene.world.showSection(util.select.fromTo(4,1,2,4,1,4), Facing.DOWN)
            scene.idle(0)
            scene
                .text(40, "Place hoppers", [5,1,4])
                .colored(PonderPalette.WHITE)
                .placeNearTarget()
            scene.idle(40)
            scene.idle(0)
            scene.world.showSection(util.select.position(4, 1, 5), Facing.DOWN)
            scene.idle(20)
            scene.idle(20)
            scene.idle(0)
            scene.world.showSection(util.select.fromTo(5,1,5,5,1,2), Facing.DOWN)
            scene.idle(20)
            scene.idle(0)
            scene.world.showSection(util.select.position(6, 1, 5), Facing.DOWN)
            scene.idle(20)
            scene.idle(0)
            scene
                .text(30, "Set the maximum delay on the redstone repeater", [8,2,5])
                .colored(PonderPalette.WHITE)
                .placeNearTarget()
            scene.idle(30)
            scene.idle(0)
            scene.world.showSection(util.select.fromTo(7,1,5,9,2,5), Facing.DOWN)//
            scene.idle(20)
            scene.addKeyframe()
            scene.idle(0)
            scene.rotateCameraY(105);
            scene.idle(20)
            scene.idle(0)
            scene.world.showSection(util.select.fromTo(4,2,2,6,2,3), Facing.DOWN)
            scene.idle(20)
            scene.addKeyframe()
            scene.idle(0)
            scene
                .text(20, "Place the iron rod", [5,2,4])
                .colored(PonderPalette.WHITE)
                .placeNearTarget()
            scene.idle(20)
            scene.idle(0)
            scene.world.showSection(util.select.fromTo(6,2,4,4,2,4), Facing.DOWN)
            scene.idle(20)
            scene.addKeyframe()
            scene.idle(0)
            scene.rotateCameraY(110);
            scene.idle(20)
            scene.idle(0)
            scene.world.showSection(util.select.fromTo(6,2,5,4,2,8), Facing.DOWN)
            scene.idle(20)
            scene.idle(0)
            scene.rotateCameraY(-105);
            scene.idle(20)
            scene.addKeyframe()
            scene.idle(0)
            scene.world.showSection(util.select.fromTo(2,2,9,8,2,11), Facing.DOWN)
            scene.idle(20)
            scene.idle(0)
            scene.world.showSection(util.select.fromTo(3,3,9,7,3,9), Facing.DOWN)
            scene.idle(20)
            scene.idle(0)
            scene.world.showSection(util.select.fromTo(4,5,9,6,4,9), Facing.DOWN)
            scene.idle(20)
            scene.idle(0)
            scene.world.showSection(util.select.fromTo(2,3,9,2,3,11), Facing.DOWN)
            scene.world.showSection(util.select.fromTo(2,3,11,8,3,11,), Facing.DOWN)
            scene.world.showSection(util.select.fromTo(8,3,9,8,3,11,), Facing.DOWN)
            scene.world.showSection(util.select.position(5, 3, 10), Facing.DOWN)
            scene.idle(20)
            scene.idle(0)
            scene
                .text(40, "Set the maximum delay on all redstone transmitters", [5,3,10])
                .colored(PonderPalette.WHITE)
                .placeNearTarget()
            scene.idle(40)
            scene.idle(0)
            scene.rotateCameraY(115);
            scene.addKeyframe()
            scene.idle(20)
            scene.idle(0)
            scene.world.showSection(util.select.fromTo(9,4,5,5,3,8,), Facing.DOWN)
            scene.idle(20)
            scene.idle(0)
            scene.world.showSection(util.select.fromTo(2,2,2,2,2,8,), Facing.DOWN)
            scene.world.showSection(util.select.fromTo(5,3,3,4,3,2,), Facing.DOWN)
            scene.world.showSection(util.select.position(3, 2, 2), Facing.DOWN)
            scene.idle(20)
            scene.addKeyframe()
            scene.idle(0)
            scene.rotateCameraY(110);
            scene.idle(20)
            scene.idle(0)
            scene
                .text(40, "Insert dry concrete into the chest", [4,5,9])
                .colored(PonderPalette.WHITE)
                .placeNearTarget()
            scene.idle(40)
            scene.addKeyframe()
            scene.idle(0)
            scene
                .text(40, "And throw any block into the funnel to start the mechanism!", [6,1,5])
                .colored(PonderPalette.WHITE)
                .placeNearTarget()
            scene.idle(40)
            scene.idle(0)
            var iron_bock = scene.world.createItemEntity(util.vector.topOf(6,1,5), (util.vector.of(0, 0, 0)),'minecraft:iron_block');
            scene.idle(20)
            scene.idle(0)
            scene.world.removeEntity(iron_bock)
            scene.idle(40)
    })
})