Ponder.registry(e => {
    e
        .create([
            'botania:entropinnyum'
        ])
        .scene("gribtweaks:mana_tnt_farm", "Лучшая ферма маны!", "kubejs:mana_tnt_farm", (scene, util) => {
            //scene.showStructure()
            scene.addKeyframe()
            scene.idle(0)
            scene.scaleSceneView(.4);
            scene.rotateCameraY(50);
            scene.world.showSection(util.select.fromTo(0, 0, 0, 10, 0, 9), Facing.DOWN)
            scene.idle(0)
            scene.addKeyframe()
            scene.idle(0)
            scene.world.showSection(util.grid.at(5, 1, 1), Facing.DOWN)
            scene.idle(40)
            scene.addKeyframe()
            scene.idle(0)
            scene
                .text(60, "Разместите 9 цветков энтропиннума (можно больше, можно парящие)", [5, 1, 4])
                .colored(PonderPalette.RED)
                .placeNearTarget()
            scene.idle(80)
            scene.idle(0)
            scene.world.showSection(util.select.fromTo(6, 1, 3, 4, 1, 5), Facing.DOWN)
            scene.idle(40)
            scene.idle(0)
            scene.world.showSection(util.grid.at(5, 3, 2), Facing.DOWN)
            scene.idle(20)
            scene
                .showControls(40, [5, 3, 2], "down")
                .rightClick()
                .withItem("botania:twig_wand")
                .whileSneaking()
            scene.overlay.showText(40)
			    .colored(PonderPalette.BLUE)
			    .text("Привяжите цветки")
                .placeNearTarget();
            scene.idle(60)
            scene.addKeyframe()
            scene.idle(0)
            scene.overlay.showText(60)
                .text("Теперь давайте построим главную часть!")
                .colored(PonderPalette.RED)
                .placeNearTarget()
            scene.idle(80)
            scene.idle(0)
            scene.world.showSection(util.select.fromTo(6, 1, 6, 4, 3, 9), Facing.DOWN)
            scene.idle(10)
            scene.idle(0)
            scene.world.showSection(util.select.fromTo(6, 4, 6, 4, 6, 9), Facing.DOWN)
            scene.idle(10)
            scene.idle(0)
            scene.world.showSection(util.select.fromTo(6, 7, 6, 4, 9, 9), Facing.DOWN)
            scene.idle(10)
            scene.addKeyframe()
            scene.idle(0)
            scene
                .text(60, "Здесь нужно поставить блок, который проводит редстоун", [6, 9, 7])
                .colored(PonderPalette.RED)
                .placeNearTarget()
            scene.idle(80)
            scene.addKeyframe()
            scene.idle(0)
            scene.world.showSection(util.select.fromTo(6, 10, 7, 5, 10, 7), Facing.DOWN)
            scene.idle(30)
            scene.idle(0)
            scene.rotateCameraY(-50);
            scene.idle(20)
            scene.idle(0)
            scene
                .showControls(40, [6, 10, 7], "down")
                .rightClick()
                .withItem('minecraft:sand')
            scene.idle(60)
            scene.idle(0)
            scene.overlay.showText(60)
                .text("Поместите 1 песок в песочные часы")
                .colored(PonderPalette.RED)
                .placeNearTarget()
            scene.idle(80)
            scene.idle(0)
            scene
                .text(60, "Любым способом поставляйте динамит в раздатчик", [6, 9, 7])
                .colored(PonderPalette.RED)
                .placeNearTarget()
            scene.idle(100)
    })
})