Ponder.registry(e => {
    e
        .create([
            'botania:orechid',
            'botania:floating_orechid'
        ])
        .scene('gribtweaks:orechid', 'Ore farm with Orechid', 'orechid', (scene, util) => {
    const redstone = util.select.fromTo(4,3,10,6,3,10)
    scene.world.setBlocks([4,2,2,6,2,7], 'minecraft:stone', false)
    scene.scaleSceneView(.7);
    scene.setSceneOffsetY(-1);
    scene.world.showSection(util.select.layer(0), Facing.UP)
    scene.idle(20)
    scene.overlay.showText(60)
			.colored(PonderPalette.WHITE)
			.text("Let's build an ore farm with Orechid")
			.placeNearTarget();
    scene.idle(80)
    scene.addKeyframe()
    scene.world.showIndependentSection(util.select.fromTo(2,1,1,8,1,9), Facing.DOWN)
    scene.idle(20)
    scene
        .text(60, "All hoppers must be directed to this one", [5, 2, 1])
        .colored(PonderPalette.WHITE)
        .placeNearTarget()
    scene.idle(80)
    scene.world.showIndependentSection(util.select.fromTo(5,1,0,6,1,0), Facing.DOWN)
    scene.idle(20)
    scene.addKeyframe()
    scene.world.showIndependentSection(util.select.position(7,2,7), Facing.DOWN)
    scene.world.showIndependentSection(util.select.position(3,2,7), Facing.DOWN)
    scene.world.showIndependentSection(util.select.position(8,2,8), Facing.DOWN)
    scene.world.showIndependentSection(util.select.position(2,2,8), Facing.DOWN)
    scene.world.showIndependentSection(util.select.position(3,2,9), Facing.DOWN)
    scene.world.showIndependentSection(util.select.position(7,2,9), Facing.DOWN)
    scene.world.showIndependentSection(util.select.position(7,3,8), Facing.DOWN)
    scene.world.showIndependentSection(util.select.position(3,3,8), Facing.DOWN)
    scene.world.showIndependentSection(util.select.fromTo(6,3,7,4,3,7), Facing.DOWN)
    scene.world.showIndependentSection(util.select.fromTo(6,3,9,4,3,9), Facing.DOWN)
    scene.idle(20)
    scene.world.showIndependentSection(util.select.fromTo(6,2,9,4,2,9), Facing.NORTH)
    scene.idle(20)
    scene.world.showIndependentSection(util.select.fromTo(7,2,8,3,2,8), Facing.DOWN)
    scene.world.showIndependentSection(util.select.fromTo(6,3,8,4,3,8), Facing.DOWN)
    scene.idle(20)
    scene.world.showSection(util.select.fromTo(4,2,1,6,2,1), Facing.DOWN)
    scene.idle(20)
    scene.rotateCameraY(-180)
    scene.idle(60)
    scene.addKeyframe()
    scene.world.showSection(util.select.fromTo(4,2,10,6,3,10), Facing.NORTH)
    scene.idle(20)
    scene.world.showSection(util.select.position(3,3,10), Facing.DOWN)
    scene.idle(30)
    scene.world.toggleRedstonePower(redstone)
    scene.world.showSection(util.select.fromTo(4,2,2,6,2,7), Facing.NORTH)
    scene.idle(8)
    scene.world.toggleRedstonePower(redstone)
    scene.idle(20)
    scene.rotateCameraY(-180)
    scene.idle(50)
    scene.addKeyframe()
    scene.world.showIndependentSection(util.select.fromTo(3,2,2,3,2,6), Facing.EAST)
    scene.idle(20)
    scene
        .text(60, "Place five redstone spreaders with mine lens", [3, 3, 4])
        .colored(PonderPalette.WHITE)
        .placeNearTarget()
    scene.idle(80)
    scene.world.showSection(util.select.fromTo(2,2,2,2,2,6), Facing.EAST)
    scene.idle(20)
    scene.world.showSection(util.select.fromTo(3,3,2,3,4,6), Facing.DOWN)
    scene.idle(20)
    scene.world.showSection(util.select.position(3,4,1), Facing.DOWN)
    scene.idle(20)
    scene
        .text(60, "Put 8 red sand in this hourglass", [3, 5, 1])
        .colored(PonderPalette.WHITE)
        .placeNearTarget()
        .attachKeyFrame()
    scene.idle(80)
    scene.world.showIndependentSection(util.select.fromTo(4,3,1,6,3,1), Facing.DOWN)
    scene.idle(20)
    scene.world.showSection(util.select.fromTo(4,4,1,6,4,1), Facing.DOWN)
    scene.idle(30)
    scene.overlay.showText(60)
			.colored(PonderPalette.WHITE)
			.text("Farm started working!")
			.placeNearTarget();
    scene.idle(90)
    })
})