ServerEvents.recipes(event => {
	event.custom({"type":"minecraft:crafting_shaped","result":{"item":"ender_pearl","count":6},"pattern":[" E ","EEE"," E "],"key":{"E":{"item":"ftbic:antimatter"}}})
    event.custom({"type":"minecraft:crafting_shaped","result":{"item":"grass_block","count":24},"pattern":["GG ","   ","   "],"key":{"G":{"item":"ftbic:antimatter"}}})
	event.custom({"type":"minecraft:crafting_shaped","result":{"item":"oak_log","count":8},"pattern":[" E ","   ","   "],"key":{"E":{"item":"ftbic:antimatter"}}})
	event.custom({"type":"minecraft:crafting_shaped","result":{"item":"emerald","count":6},"pattern":[" E ","EEE"," E "],"key":{"E":{"item":"gribtweaks:advanced_antimatter"}}})
	event.custom({"type":"minecraft:crafting_shaped","result":{"item":"diamond","count":6},"pattern":[" E ","E E"," E "],"key":{"E":{"item":"gribtweaks:advanced_antimatter"}}})
	event.custom({"type":"minecraft:crafting_shaped","result":{"item":"naturesaura:tainted_gold","count":6},"pattern":["   ","MMM","M  "],"key":{"M":{"item":"gribtweaks:advanced_antimatter"}}})
	event.custom({"type":"minecraft:crafting_shaped","result":{"item":"ftbic:iridium_ingot","count":6},"pattern":["GGG","   ","   "],"key":{"G":{"item":"gribtweaks:advanced_antimatter"}}})
	event.custom({"type":"minecraft:crafting_shaped","result":{"item":"ftbic:tin_ingot","count":12},"pattern":["   "," O "," OO"],"key":{"O":{"item":"gribtweaks:advanced_antimatter"}}})
	event.custom({"type":"minecraft:crafting_shaped","result":{"item":"gold_ingot","count":12},"pattern":["   ","WW ","W  "],"key":{"W":{"item":"gribtweaks:advanced_antimatter"}}})
	event.custom({"type":"minecraft:crafting_shaped","result":{"item":"iron_ingot","count":12},"pattern":["  B"," B ","  B"],"key":{"B":{"item":"gribtweaks:advanced_antimatter"}}})
	event.custom({"type":"minecraft:crafting_shaped","result":{"item":"ftbic:lead_ingot","count":12},"pattern":[" M "," M ","M  "],"key":{"M":{"item":"gribtweaks:advanced_antimatter"}}})
	event.custom({"type":"minecraft:crafting_shaped","result":{"item":"ftbic:aluminum_ingot","count":8},"pattern":[" EE","   ","   "],"key":{"E":{"item":"gribtweaks:advanced_antimatter"}}})
	event.custom({"type":"minecraft:crafting_shaped","result":{"item":"copper_ingot","count":16},"pattern":["GG ","GG ","   "],"key":{"G":{"item":"gribtweaks:advanced_antimatter"}}})
	event.custom({"type":"minecraft:crafting_shaped","result":{"item":"quartz","count":24},"pattern":["B B"," B ","   "],"key":{"B":{"item":"gribtweaks:advanced_antimatter"}}})
	event.custom({"type":"minecraft:crafting_shaped","result":{"item":"blaze_rod","count":6},"pattern":["   ","M  ","M  "],"key":{"M":{"item":"gribtweaks:advanced_antimatter"}}})
	event.custom({"type":"minecraft:crafting_shaped","result":{"item":"redstone","count":8},"pattern":["  X","   ","   "],"key":{"X":{"item":"gribtweaks:advanced_antimatter"}}})
	event.custom({"type":"minecraft:crafting_shaped","result":{"item":"glowstone","count":8},"pattern":[" E ","  E","   "],"key":{"E":{"item":"gribtweaks:advanced_antimatter"}}})
	event.custom({"type":"minecraft:crafting_shaped","result":{"item":"amethyst_shard","count":18},"pattern":["G  "," G ","  G"],"key":{"G":{"item":"gribtweaks:advanced_antimatter"}}})
})