StartupEvents.registry('block', e => {
e.create('twilightforest:osmium_ore')
    .soundType('stone')
    .hardness(2)
    .displayName('Osmium ore') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_iron_tool')
    .tag('forge:ores')
    .requiresTool(true)
    // .item(itemBuilder => {
    //     itemBuilder
    //         .tooltip('Генерируется на островах Twilight Forest')
    // }) 
    // TODO: FIX????
e.create('twilightforest:block_osmium')
    .soundType('metal')
    .hardness(2)
    .displayName('Osmium Block') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_iron_tool')
    .tag('forge:storage_blocks/osmium')
    .tag('forge:storage_blocks')
    .requiresTool(true)
e.create('hexerei:witch_ore')
    .soundType('stone')
    .hardness(2)
    .displayName('Witch ore') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_diamond_tool')
    .tag('forge:ores')
    .requiresTool(true)
    .item(itemBuilder => {
        itemBuilder
            .tooltip('§5Генерируется на островах Twilight Forest')
    })
e.create('hexerei:witch_ingot_block')
    .soundType('metal')
    .hardness(3)
    .displayName('Witch ingot block') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_diamond_tool')
    .tag('forge:storage_blocks')
    .requiresTool(true)
    
    })