StartupEvents.registry('block', e => {
e.create('twilightforest:osmium_ore')
    .material('stone')
    .hardness(2)
    .displayName('Osmium ore') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_iron_tool')
    .tag('forge:ores')
    .requiresTool(true)
    .item(itemBuilder => {
        itemBuilder
            .tooltip('Генерируеться на любом острове Twilight Forest на высоте от -32 до 0')
    })
e.create('twilightforest:block_osmium')
    .material('metal')
    .hardness(2)
    .displayName('Osmium Block') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_iron_tool')
    .tag('forge:storage_blocks/osmium')
    .tag('forge:storage_blocks')
    .requiresTool(true)
e.create('hexerei:witch_ore')
    .material('stone')
    .hardness(2)
    .displayName('Witch ore') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_diamond_tool')
    .tag('forge:ores')
    .requiresTool(true)
    .item(itemBuilder => {
        itemBuilder
            .tooltip('§5Генерируеться на любом острове Twilight Forest на высоте от -16 до 4')
    })
e.create('hexerei:witch_ingot_block')
    .material('metal')
    .hardness(3)
    .displayName('Witch ingot block') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_diamond_tool')
    .tag('forge:storage_blocks')
    .requiresTool(true)
    
    })