StartupEvents.registry('block', e => {
e.create('gribtweaks:osmium_ore')
    .soundType('stone')
    .hardness(3)
    .displayName('Осмиевая руда') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_iron_tool')
    .tag('forge:ores')
    .requiresTool(true)
e.create('gribtweaks:block_osmium')
    .soundType('metal')
    .hardness(5)
    .displayName('Осмиевый блок') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_iron_tool')
    .tag('forge:storage_blocks/osmium')
    .tag('forge:storage_blocks')
    .requiresTool(true)
e.create('gribtweaks:witch_ore')
    .soundType('stone')
    .hardness(3)
    .displayName('Ведьминская руда') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_diamond_tool')
    .tag('forge:ores')
    .requiresTool(true)

e.create('gribtweaks:witch_ingot_block')
    .soundType('metal')
    .hardness(5)
    .displayName('Ведьминский блок') 
    .tagBlock('minecraft:mineable/pickaxe') 
    .tagBlock('minecraft:needs_diamond_tool')
    .tag('forge:storage_blocks')
    .requiresTool(true)
    
})